services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx.config:/etc/nginx/conf.d/default.conf
      - ./:/var/www/todo/
  php:
    build:
      context: .
      dockerfile: dockerfiles/DockerFile
    volumes:
      - ./:/var/www/todo/
    depends_on:
      - mysql

  mysql:
    image: "mysql:8.0"
    ports:
      - "3316:3306"
    env_file:
      - ./config/mysql.env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: