FROM php:8.4-fpm-alpine 

WORKDIR /var/www/todo

RUN docker-php-ext-install pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY composer.json /var/www/todo/

RUN composer update

RUN composer install --no-dev --optimize-autoloader

COPY . /var/www/todo/